"""Add trade fields to country

Revision ID: f1af1efeb8c2
Revises: 74db1a9153aa
Create Date: 2026-07-20 20:36:34.964999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1af1efeb8c2'
down_revision: Union[str, Sequence[str], None] = '74db1a9153aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('code', sa.String(length=3), nullable=True))
    op.add_column('countries', sa.Column('flag', sa.String(length=10), nullable=True))
    op.add_column('countries', sa.Column('gdp', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('imports', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('exports', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('top_commodity', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('countries', sa.Column('trade_rank', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'countries', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_column('countries', 'trade_rank')
    op.drop_column('countries', 'risk_level')
    op.drop_column('countries', 'top_commodity')
    op.drop_column('countries', 'exports')
    op.drop_column('countries', 'imports')
    op.drop_column('countries', 'gdp')
    op.drop_column('countries', 'flag')
    op.drop_column('countries', 'code')
    # ### end Alembic commands ###
